---
title: "Challenge - Performance Measures"
author: "Jamila Rzayeva"
date: "2022-06-12"
output:
  html_document:
    toc: true
    toc_float: true
    collapsed: false
    number_sections: false
    toc_depth: 3
    #code_folding: hide
---
```{css, echo=FALSE}
body {
  color: white;
  background-color: #ffc1cc;
  font-family: Futura;
}
.list-group-item, .list-group-item.active, .list-group-item.active:focus, .list-group-item.active:hover {
  color: white;
  background-color: #ff758d ;
  border-color: #white;
  border-width: 5px;
}
```

```{r setup, include=FALSE}
knitr::opts_chunk$set(message=FALSE,warning=FALSE, cache=TRUE)
```

# Challenge: Performance Measures

## Load libraries and data

```{r, fig.height= 12 }
#Load Libraries
library(tidyverse)
library(readxl)
library(skimr)
library(GGally)
library(DT)

# <3 <3 <3 <3 <3 <3 <3 <3 <3 <3 <3 <3 <3 <3 <3 <3 <3
library("wesanderson") # <3 <3 <3 <3 <3 <3 <3 <3 <3 
# <3 <3 <3 <3 <3 <3 <3 <3 <3 <3 <3 <3 <3 <3 <3 <3 <3

# Table Help
color <- toString(wes_palette("Royal2", 5, type="discrete")[5])
longString = paste("$(this.api().table().header()).css({'color':'#ffff', 'background-color' : '", 
                   color, 
                   "'});") #Format the table header

pretty.tables <- function(tb1) {
    datatable(tb1, class = 'cell-border stripe', 
              rownames = FALSE,
              options = list(
                initComplete = JS(
                  "function(settings, json) {", 
                  longString ,
                  "}")))
}

#Import Data
backorders_tb1 <- read_csv("C:/Users/alexa/Documents/Germany/Hamburg2020/TUHH/SuSe 2021/BWL/ml_journal-adarche/raw_data/product_backorders.csv")

#Recipie (Same as previous challenge) 
set.seed(seed = 1349)
split_obj <- rsample::initial_split(backorders_tb1, prop = 0.75)

# Assign training and test data
train_readable_tb1 <- training(split_obj)
test_readable_tb1  <- testing(split_obj)

factor_names <- c("went_on_backorder")
recipie <- recipe(went_on_backorder ~ ., data = train_readable_tb1) %>%  
           step_zv(all_predictors()) %>% 
           step_mutate_at(factor_names, fn = as.factor) %>%
           step_center(all_numeric()) %>%
           step_scale(all_numeric()) %>%
           step_dummy(all_nominal(), -all_outcomes()) %>% 
           prep()

training <- bake(recipie, new_data = train_readable_tb1)
testing  <- bake(recipie, new_data = test_readable_tb1)

training <- bake(recipie, new_data = train_readable_tb1)
testing <- bake(recipie, new_data = test_readable_tb1)

#H2O Testing Set up (Same as previous challenge)
h2o.init()
split_h2o <- h2o.splitFrame(as.h2o(training), ratios = c(0.75), seed = 1435)
train_h2o <- split_h2o[[1]]
valid_h2o <- split_h2o[[2]]
test_h2o  <- as.h2o(testing)

y <- "went_on_backorder"
x <- setdiff(names(train_h2o), y)

h2o_model <- h2o.automl(x = x,
                        y = y,
                        training_frame    = train_h2o,
                        validation_frame  = valid_h2o,
                        leaderboard_frame = test_h2o,
                        max_runtime_secs  = 30,
                        nfolds            = 5)
```

## Leaderboard visualization

```{r, fig.height= 12 }
# Transform data
gain_tf_tb1 <- h2o_model@leaderboard %>%
                   as_tibble() %>%
                   select(-c(aucpr, mean_per_class_error, rmse, mse)) %>% 
                   mutate(model_type = str_extract(model_id, "[^_]+")) %>%
                   slice(1:n()) %>% 
                   rownames_to_column(var = "rowname") %>%
                   mutate(
                     model_id   = as_factor(model_id),
                     model_type = as.factor(model_type)
                   ) %>% 
                   pivot_longer(cols = -c(model_id, model_type, rowname), 
                                names_to = "key", 
                                values_to = "value", 
                                names_transform = list(key = forcats::fct_inorder)
                   )

# Visualize Data
gain_tf_tb1 %>%
  ggplot(aes(value, model_id, color = model_type)) +
  geom_point(size = 3) +
  scale_color_manual(values = wes_palette("Darjeeling1", 6, type = "continuous")) +
  geom_label(aes(label = round(value, 3), hjust = "inward"), show.legend = F) +
  labs(title = "Leaderboard Metrics",
       subtitle = paste0("Ordered by: ", "AUC"),
       y = "Model Postion, Model ID", x = "") + 
  theme(legend.position = "bottom")

#Save for l8er
#h2o.getModel("DeepLearning_1_AutoML_20210531_122304") %>%
#          h2o.saveModel(path = "raw_data/")
```

## Tune a model with grid search

```{r, fig.height= 12 }
h2o.init()
#Reload the data from previous session
deeplearning_h2o <- h2o.loadModel("raw_data/DeepLearning_1_AutoML_20210531_122304")
h2o.performance(deeplearning_h2o, newdata = as.h2o(testing))

deeplearning_grid <- h2o.grid(algorithm = "deeplearning",
                              grid_id = "deeplearning_grid",
                              # prediction/response
                              x = x,
                              y = y,
                              # training and validation
                              training_frame   = train_h2o,
                              validation_frame = valid_h2o,
                              nfolds = 5,
                              hyper_params = list(
                                hidden = list(c(10, 10, 10), c(50, 20, 10), c(20, 20, 20)),
                                epochs = c(10, 25, 50, 75, 100))
                              )

#This takes sooooo long to run
h2o.getGrid(grid_id = "deeplearning_grid", sort_by = "auc", decreasing = TRUE)

deeplearning_grid_model_1 <- h2o.getModel("deeplearning_grid_model_1")
deeplearning_grid_model_1 %>% h2o.auc(train = T, valid = T, xval = T)

deeplearning_grid_model_1 %>% h2o.performance(newdata = as.h2o(testing))

```

# Pretty Graphs
Visualize the trade of between the precision and the recall and the optimal threshold

```{r, fig.height= 12 }
performance <- h2o.performance(deeplearning_h2o, newdata = as.h2o(testing))

typeof(performance)
performance %>% slotNames()
performance@metrics
h2o.auc(performance, train = T, valid = T, xval = T)
h2o.auc(deeplearning_h2o, train = T, valid = T, xval = T)
h2o.giniCoef(performance)
h2o.logloss(performance)
h2o.confusionMatrix(deeplearning_h2o)
h2o.confusionMatrix(performance)

performance_tb1 <- performance %>%
    h2o.metric() %>%
    as.tibble() 

performance_tb1 %>%
    filter(f1 == max(f1))

performance_tb1 %>%
    ggplot(aes(x = threshold)) +
    geom_line(aes(y = precision), color = wes_palette("FantasticFox1", 3)[3], size = 1) +
    geom_line(aes(y = recall), color = wes_palette("FantasticFox1", 4)[4], size = 1) +
    # Intercept Line
    geom_vline(xintercept = h2o.find_threshold_by_max_metric(performance, "f1")) +
    labs(title = "Precision and Recall", y = "Value", x="Threshhold")

#Save models for later
#for (i in c(1,2,3,4,5,6,7)){
#  model_name <- h2o_model@leaderboard %>%
#    as.tibble() %>%
#    slice(i) %>%
#    pull(model_id)
#    model_retrieved <- h2o.getModel(model_name)%>%
#    h2o.saveModel(path = "raw_data/H2O/")
#}
```

## ROC Plot

```{r, fig.height= 12 }
#Reload Data
path <- "raw_data/H2O/DeepLearning_1_AutoML_20210531_122304"

#Helper Function
get_models <- function(path, testing) {
    model_h2o <- h2o.loadModel(path)
    performance  <- h2o.performance(model_h2o, newdata = as.h2o(testing)) 
    
    performance %>% h2o.metric() %>%
                    as_tibble() %>%
                    mutate(auc = h2o.auc(performance)) %>%
                    select(tpr, fpr, auc)
}

metrics_tb1 <- fs::dir_info(path = "raw_data/H2O/") %>%
    select(path) %>%
    mutate(metrics = map(path, get_models, testing)) %>%
    unnest(cols = metrics)

metrics_tb1 %>% mutate(path = str_split(path, pattern = "/", simplify = T)[,3] %>% as_factor(),
                      auc  = auc %>% round(3) %>% as.character() %>% as_factor()) %>%
                      ggplot(aes(fpr, tpr, color = path, linetype = auc)) +
                      geom_line(size = 1) +
                      geom_abline(color=wes_palette("Darjeeling1", 1), linetype = "dotted") +
                      theme(
                        legend.direction = "vertical",
                        legend.position = "bottom"
                        ) +
                      labs(
                          title = "ROC Plot",
                          subtitle = "Top Performing Models Metrics"
                      )
```

## Precision vs Recall Plot

```{r, fig.height= 12 }
get_models <- function(path, testing) {
    model_h2o <- h2o.loadModel(path)
    perf_h2o  <- h2o.performance(model_h2o, newdata = as.h2o(testing)) 
    
    perf_h2o %>% h2o.metric() %>%
                 as_tibble() %>%
                 mutate(auc = h2o.auc(perf_h2o)) %>%
                 select(tpr, fpr, auc, precision, recall)
}

metrics_tb1 <- fs::dir_info(path = "raw_data/H2O/") %>%
               select(path) %>%
               mutate(metrics = map(path, get_models, testing)) %>%
               unnest(cols = metrics)

metrics_tb1 %>% mutate(path = str_split(path, pattern = "/", simplify = T)[,3] %>% as_factor(),
                       auc  = auc %>% round(3) %>% as.character() %>% as_factor()) %>%
                ggplot(aes(recall, precision, color = path, linetype = auc)) +
                geom_line(size = 1) +
                theme(
                  legend.direction = "vertical",
                  legend.position = "bottom"
                  ) +
                labs(
                    title = "Precision vs Recall Plot",
                    subtitle = "Top Performing Models"
                )
```

## Gain Chart

```{r, fig.height= 12 }
lifted_tb1 <- performance %>%
            h2o.gainsLift() %>%
            as.tibble()
gain_tf_tb1 <- lifted_tb1 %>% 
                   select(group, 
                          cumulative_data_fraction, 
                          cumulative_capture_rate, 
                          cumulative_lift) %>%
                   select(-contains("lift")) %>%
                   mutate(baseline = cumulative_data_fraction) %>%
                   rename(gain     = cumulative_capture_rate) %>%
                   # Easier to plot colors
                   pivot_longer(cols = c(gain, baseline), values_to = "value", names_to = "key")

gain_tf_tb1 %>% ggplot(aes(x = cumulative_data_fraction, y = value, color = key)) +
                    geom_line(size = 1.5) +
                    labs(
                        title = "Gain Chart",
                        x = "Data Fraction (Cumulative)",
                        y = "Gain"
                    )
```

## Lift Chart

```{r, fig.height= 12 }
lift_tf_tb1 <- lifted_tb1 %>% 
               select(group, cumulative_data_fraction, cumulative_capture_rate, cumulative_lift) %>%
               select(-contains("capture")) %>%
               mutate(baseline = 1) %>%
               rename(lift = cumulative_lift) %>%
               pivot_longer(cols = c(lift, baseline), values_to = "value", names_to = "key")

lift_tf_tb1 %>% ggplot(aes(x = cumulative_data_fraction, y = value, color = key)) +
                geom_line(size = 1.5) +
                labs(
                    title = "Lift Chart",
                    x = "Data Fraction (Cumulative)",
                    y = "Lift"
                ) 
```

## Dashboard with cowplot

```{r, fig.height= 12 }
library(cowplot)
library(glue)

#Set values
h2o_leaderboard <- h2o_model@leaderboard
newdata <- testing
order_by <- "auc"
max_models <- 4
size <- 1

#Helper Function
performance_plot_help <- function(h2o_leaderboard, newdata, order_by = c("auc", "logloss"),
                                   max_models = 3, size = 1.5) {
        
  # Handy Defs
  leaderboard_tb1 <- h2o_leaderboard %>%
                     as_tibble() %>%
                     slice(1:max_models)
  
  newdata_tbl <- newdata %>%
                 as_tibble()
      
  order_by <- tolower(order_by[[1]]) 
  order_by_expr <- rlang::sym(order_by)
    h2o.no_progress()
  
  # Model metrics
  get_model_performance_metrics <- function(model_id, testing) {
      model_h2o <- h2o.getModel(model_id)
      perf_h2o  <- h2o.performance(model_h2o, newdata = as.h2o(testing))
      perf_h2o %>% h2o.metric() %>%
                   as.tibble() %>%
                   select(threshold, tpr, fpr, precision, recall)
  }
  
  metrics_tb1 <- leaderboard_tb1 %>%
                 mutate(metrics = map(model_id, get_model_performance_metrics, newdata_tbl)) %>%
                 unnest(cols = metrics) %>%
                 mutate(
                 model_id = as_factor(model_id) %>% 
                            # programmatically reorder factors depending on order_by
                            fct_reorder(!! order_by_expr, 
                                        .desc = ifelse(order_by == "auc", TRUE, FALSE)),
                 auc      = auc %>% 
                            round(3) %>% 
                            as.character() %>% 
                            as_factor() %>% 
                            fct_reorder(as.numeric(model_id)),
                 logloss  = logloss %>% 
                            round(4) %>% 
                            as.character() %>% 
                            as_factor() %>% 
                            fct_reorder(as.numeric(model_id))
                 )
  
  # 1A. ROC Plot
  p1 <- metrics_tb1 %>%
        ggplot(aes(fpr, tpr, color = model_id, linetype = !! order_by_expr)) +
        geom_line(size = size) +
        labs(title = "ROC", x = "FPR", y = "TPR") +
        theme(legend.direction = "vertical") 
      
  # 1B. Precision vs Recall
  p2 <- metrics_tb1 %>%
        ggplot(aes(recall, precision, color = model_id, linetype = !! order_by_expr)) +
        geom_line(size = size) +
        labs(title = "Precision Vs Recall", x = "Recall", y = "Precision") +
        theme(legend.position = "none") 
  
  # 2. Gain / Lift
  get_gain_lift <- function(model_id, testing) {
      model_h2o <- h2o.getModel(model_id)
      perf_h2o  <- h2o.performance(model_h2o, newdata = as.h2o(testing)) 
      perf_h2o %>% h2o.gainsLift() %>%
                   as.tibble() %>%
                   select(group, cumulative_data_fraction, cumulative_capture_rate, cumulative_lift)
  }
  
  lifted_tb1 <- leaderboard_tb1 %>%
      mutate(metrics = map(model_id, get_gain_lift, newdata_tbl)) %>%
      unnest(cols = metrics) %>%
      mutate(
          model_id = as_factor(model_id) %>% 
              fct_reorder(!! order_by_expr, 
                          .desc = ifelse(order_by == "auc", TRUE, FALSE)),
          auc  = auc %>% 
              round(3) %>% 
              as.character() %>% 
              as_factor() %>% 
              fct_reorder(as.numeric(model_id)),
          logloss = logloss %>% 
              round(4) %>% 
              as.character() %>% 
              as_factor() %>% 
              fct_reorder(as.numeric(model_id))
      ) %>%
      rename(
          gain = cumulative_capture_rate,
          lift = cumulative_lift
      ) 
  
  # 2A. Gain Plot
  p3 <- lifted_tb1 %>%
        ggplot(aes(cumulative_data_fraction, gain, 
                          color = model_id, linetype = !! order_by_expr)) +
        geom_line(size = size,) +
        geom_segment(x = 0, y = 0, xend = 1, yend = 1, 
                     color = "red", size = size, linetype = "dotted") +
        expand_limits(x = c(0, 1), y = c(0, 1)) +
        labs(title = "Gain",
             x = "Cumulative Data Fraction", y = "Gain") +
        theme(legend.position = "none")
  
  # 2B. Lift Plot
  p4 <- lifted_tb1 %>%
        ggplot(aes(cumulative_data_fraction, lift, 
                          color = model_id, linetype = !! order_by_expr)) +
        geom_line(size = size) +
        geom_segment(x = 0, y = 1, xend = 1, yend = 1, 
                     color = "red", size = size, linetype = "dotted") +
        expand_limits(x = c(0, 1), y = c(0, 1)) +
        labs(title = "Lift",
             x = "Cumulative Data Fraction", y = "Lift") +
        theme(legend.position = "none") 
    
  
  # Combine using cowplot
  p_legend <- get_legend(p1)
  p1 <- p1 + theme(legend.position = "none")
  
  # combine multiple plots
  p <- cowplot::plot_grid(p1, p2, p3, p4, ncol = 2)
  
  # drawing layer
  p_title <- ggdraw() + 
  
      # draw text on a ggdraw layer / ggplot object
      draw_label("H2O Model Metrics", size = 18, fontface = "bold", color = "#2C3E50")
  p_subtitle <- ggdraw() + 
      draw_label(glue("Ordered by {toupper(order_by)}"), size = 10, color = "#2C3E50")
  # The whole enchilada
  ret <- plot_grid(p_title, p_subtitle, p, p_legend, 
                   # Make sure everything fits
                   ncol = 1, rel_heights = c(0.05, 0.05, 1, 0.05 * max_models))
  h2o.show_progress()
  return(ret)
}

h2o_model@leaderboard %>%
    performance_plot_help(newdata = testing, order_by = "logloss", 
                          size = 0.5, max_models = 4)
```